<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="base_length" value="0.35"/>
    <xacro:property name="base_width" value="0.26"/>
    <xacro:property name="base_height" value="0.01"/>
    <xacro:property name="wheel_radius" value="0.03"/>
    <xacro:property name="wheel_length" value="0.015"/>
    <xacro:property name="caster_radius" value="${wheel_radius / 1.5}"/>
    <xacro:property name="shaft_length" value="0.017"/>
    <xacro:property name="shaft_radius" value="0.005"/>

    

    <link name="base_footprint"/>
    <link name="odom"/>
   

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
            <material name="white"/>
        </visual>
        <xacro:box_inertia m="5.0" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}"
         xyz="0 0 ${2*base_height / 2.0}" rpy="0 0 0" />
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
        </collision>
    </link>

    <link name="layer1">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
            <material name="white"/>
        </visual>
        <xacro:box_inertia m="5.0" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}"
         xyz="0 0 ${2*base_height / 2.0}" rpy="0 0 0" />
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
        </collision>
    </link>

    <link name="layer2">
        <visual>
            <geometry>
                <box size="${base_length-0.22} ${base_width-0.08} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
            <material name="white"/>
        </visual>
        <xacro:box_inertia m="5.0" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}"
         xyz="0 0 ${2*base_height / 2.0}" rpy="0 0 0" />
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
        </collision>
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2.0} 0 0"/>
                <material name ="grey"/>
            </visual>
            <xacro:cylinder_inertia m="1.0" r="${2*wheel_radius}" h="${2*wheel_length}" xyz="0 0 0" rpy="${pi/2.0} 0 0"/>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2.0} 0 0"/>
            </collision>
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="left"/>
    <xacro:wheel_link prefix="right"/>


    <xacro:macro name="front_shaft_link" params="prefix">
        <link name="front_${prefix}_shaft_link">
            <visual>
                 <geometry>
                     <cylinder radius="${shaft_radius}" length="0.143"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <material name ="grey"/>
            </visual>
            <xacro:cylinder_inertia m="0.5" r="${shaft_radius}" h="${shaft_length}" xyz="0 0 0" rpy="0 0 0"/>
            <collision>
                <geometry>
                    <cylinder radius="${shaft_radius}" length="${shaft_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </collision>
        </link>
    </xacro:macro>

    <xacro:front_shaft_link prefix="right"/>
    <xacro:front_shaft_link prefix="left"/>

    <xacro:macro name="rear_shaft_link" params="prefix">
        <link name="rear_${prefix}_shaft_link">
            <visual>
                 <geometry>
                     <cylinder radius="${shaft_radius}" length="${0.07}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <material name ="grey"/>
            </visual>
            <xacro:cylinder_inertia m="0.5" r="${shaft_radius}" h="${shaft_length}" xyz="0 0 0" rpy="0 0 0"/>
            <collision>
                <geometry>
                    <cylinder radius="${shaft_radius}" length="${shaft_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </collision>
        </link>
    </xacro:macro>

    <xacro:rear_shaft_link prefix="right"/>
    <xacro:rear_shaft_link prefix="left"/>

    <link name="front_caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="grey"/>
        </visual>
        <xacro:sphere_inertia m="0.5" r="${2*caster_radius}" xyz="0 0 0" rpy="0 0 0" />
        <collision>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
    </link>

    <link name="rear_caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="grey"/>
        </visual>
        <xacro:sphere_inertia m="0.5" r="${2*caster_radius}" xyz="0 0 0" rpy="0 0 0" />
        <collision>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
    </link>

    <link name="laser_frame">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length+0.02}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2.0} 0 0"/>
            <material name ="blue"/>
        </visual>
        <xacro:cylinder_inertia m="1.0" r="${2*wheel_radius}" h="${2*wheel_length}" xyz="0 0 0" rpy="${pi/2.0} 0 0"/>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2.0} 0 0"/>
        </collision>
    </link>


    <joint name="odom" type="fixed">
        <parent link="odom"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <joint name="layer1_joint" type="fixed">
        <parent link="base_link"/>
        <child link="layer1"/>
        <origin xyz="0 0 0.07" rpy="0 0 0"/>
    </joint>

    <joint name="layer2_joint" type="fixed">
        <parent link="layer1"/>
        <child link="layer2"/>
        <origin xyz="-0.08 0 0.07" rpy="0 0 0"/>
    </joint>

    <joint name="front_right_shaft_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_right_shaft_link"/>
        <origin xyz="-0.08 0.07 0.079" rpy="0 0 0"/>
    </joint>

    <joint name="front_left_shaft_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_left_shaft_link"/>
        <origin xyz="-0.08 -0.07 0.079" rpy="0 0 0"/>
    </joint>

    <joint name="rear_right_shaft_joint" type="fixed">
        <parent link="base_link"/>
        <child link="rear_right_shaft_link"/>
        <origin xyz="0.08 0.07 0.0455" rpy="0 0 0"/>
    </joint>

    <joint name="rear_left_shaft_joint" type="fixed">
        <parent link="base_link"/>
        <child link="rear_left_shaft_link"/>
        <origin xyz="0.08 -0.07 0.0455" rpy="0 0 0"/>
    </joint>


    <joint name="right_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="0 ${-((base_width / 2.0) + (wheel_length/2.0))} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit velocity="100" effort="100"/>
    </joint>

    <joint name="left_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="0 ${(base_width / 2.0) + (wheel_length/2.0)} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit velocity="100" effort="100"/>
    </joint>

    <joint name="rear_caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="rear_caster_wheel_link"/>
        <origin xyz="${base_length - 0.2} 0 ${-caster_radius}" rpy="0 0 0"/>
    </joint>

  <joint name="front_caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_caster_wheel_link"/>
        <origin xyz="${(-base_length) + 0.2} 0 ${-caster_radius}" rpy="0 0 0"/>
    </joint>

    <joint name="laser_joint" type="fixed">
       <parent link="layer2"/>
       <child link="laser_frame"/>
       <origin xyz="0 0 0.015" rpy="300 0 0"/>
    </joint>

    <transmission name="left_wheel_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="left_wheel_joint">
         <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface> <!-- or velocity -->
      </joint>
      <actuator name="left_motor">
         <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <transmission name="right_wheel_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="right_wheel_joint">
         <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface> <!-- or velocity -->
      </joint>
      <actuator name="right_motor">
         <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

</robot>
